### ISSUE TITLE
Support for copy and paste of infrastructure specific alert conditions.

### ISSUE THREAD

**Issue by psi09** [newrelic-experimental/nr-account-migration#3]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
Feature should do backup of infrastructure specific conditions and restoration of them across multiple NR accounts with POST and PUT request.

## Desired Behavior

Feature should update the existing infrastructure condition or create the new one if applicable.

export NEW_RELIC_ONE_AC=""
&
export NEW_RELIC_ANOTHER_AC=""

Usage: $(basename "$0") --fromoneacpolicyid="" --toanotheracpolicyid=""
## Possible Solution

A shell script or any utility as such.

**NOTE:** will be raising a PR for such issue as have one working shell script to use.
## Additional context

Migration of such conditions were the requirement.

**NOTE:** another pull request should allow us to modify the parameters/attributes of the conditions based on where its getting copied to.

**Comment by bpeckNR** [comment]
Infrastructure alert support using Python was added in https://github.com/newrelic-experimental/nr-account-migration/pull/14/.

**Comment by adiosspandit** [comment]
Thank you @bpeckNR for implementing this :-)
