### ISSUE TITLE
migratepolicies.py issue: AttributeError: 'Namespace' object has no attribute 'sourceRegion'

### ISSUE THREAD

**Issue by ahealy-newr** [newrelic-experimental/nr-account-migration#30]
## Description

When a user runs the migratepolicies.py command they are encountering an Attribute Error:

Command Run: **python3 migratepolicies.py --fromFile output/alertpolicies --sourceAccount XXX --sourceApiKey NRAK-<redacted> --sourceRegion us --targetAccount YYY --targetApiKey NRAK-<redacted> --targetRegion eu --useLocal**

## Expected Behavior

Expect to not have errors present when running this command. Looks like a bug that was introduced from commit on May 28th

## Relevant Logs / Console output

```
Traceback (most recent call last):
  File "/Users/jonathanm/Downloads/nr-account-migration-2.2.0/migratepolicies.py", line 389, in <module>
    main()
  File "/Users/jonathanm/Downloads/nr-account-migration-2.2.0/migratepolicies.py", line 374, in main
    sourceRegion = utils.ensure_source_region(args)
  File "/Users/jonathanm/Downloads/nr-account-migration-2.2.0/library/utils.py", line 137, in ensure_source_region
    if args.sourceRegion and len(args.sourceRegion) > 0:
AttributeError: 'Namespace' object has no attribute 'sourceRegion'
```

## Your Environment

MacOS BigSur v11.3.1

## Suggested fix

Application is referencing sourceRegion and targetRegion in the args object which aren't present on multiple lines. Should use args.source_region and args.target_region appropriately. Additionally, for the migrate function called within main, these two arguments should also be passed or you will have further errors (TypeError)

**Comment by adiosspandit** [comment]
https://github.com/newrelic-experimental/nr-account-migration/releases/tag/2.2.1
Could you try this new release @ahealy-newr Thanks for the detailed bug report.
Sorry about the bug. I had tested it via the nrmig utility and didn't test this particular script via command line params.

**Comment by ahealy-newr** [comment]
Looks good to me @adiosspandit. Checked it there. Thanks for the quick turnaround
