### ISSUE TITLE
migratemonitors.py: supply mapping file for (private) minions

### ISSUE THREAD

**Issue by crshanks** [newrelic-experimental/nr-account-migration#38]
## Summary

Allow mapping of minion locations when migrating monitors. This is particularly important when migrating between regions, for example US to EU, as the private minion locations will not have the same location.

## Desired Behavior

When migrating monitors allow the mapping of monitor locations, which is especially important when migrating between regions.

## Possible Solution

An optional command line flag can be passed to reference a mapping file JSON dictionary, e.g.

```
{
  "1234567-aws_minion-D96": "9876543-nr_cpm_aws-556",
  "1234567-aws_minion-696": "9876543-nr_cpm_aws-F30"
}

```

## Additional context

This may be a duplicate of issue #31. A PR with optional config flag and supplied mapping file, with example will be submitted shortly for consideration.

**Comment by adiosspandit** [comment]
Fixed in https://github.com/newrelic-experimental/nr-account-migration/pull/39
